apiVersion: apps/v1
kind: Deployment
metadata:
  name: raman-deploy
  namespace: raman
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu-deploy
  template:
    metadata:
      labels:
        app: ubuntu-deploy
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 3600; done;"]
        tty: true
        volumeMounts:
          - name: azure
            mountPath: /var/www/html
      volumes:
      - name: azure
        persistentVolumeClaim:
          claimName: raman-pvc
